# Generated by Django 2.2 on 2020-02-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_username', models.CharField(max_length=32, unique=True)),
                ('l_tell', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fly_boss',
            },
        ),
        migrations.CreateModel(
            name='Bupi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_bossname', models.CharField(max_length=32)),
                ('b_name', models.CharField(max_length=100)),
                ('b_price', models.FloatField(default=0)),
                ('b_storenums', models.IntegerField(default=0)),
                ('b_meters', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'fly_bupi',
            },
        ),
        migrations.CreateModel(
            name='Cairecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cai_bupin', models.CharField(max_length=100)),
                ('twonine', models.IntegerField(default=0)),
                ('treezero', models.IntegerField(default=0)),
                ('treeone', models.IntegerField(default=0)),
                ('treetwo', models.IntegerField(default=0)),
                ('cai_price', models.FloatField(default=0)),
                ('cai_nums', models.IntegerField(default=0)),
                ('cai_meter', models.FloatField(default=0)),
                ('cai_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fly_caicord',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_allprice', models.FloatField(default=0)),
                ('o_meters', models.FloatField(default=0)),
                ('o_pishu', models.IntegerField(default=0)),
                ('o_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fly_order',
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_nums', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fly_pants',
            },
        ),
        migrations.CreateModel(
            name='Sendorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_o_worker', models.CharField(max_length=32)),
                ('s_o_allprice', models.FloatField(default=0)),
                ('s_o_nums', models.IntegerField(default=0)),
                ('s_o_pishu', models.IntegerField(default=0)),
                ('s_o_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fly_sendorder',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=32, unique=True)),
                ('w_tell', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fly_worker',
            },
        ),
        migrations.CreateModel(
            name='Sendorderitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soi_pname', models.CharField(max_length=64)),
                ('soi_price', models.FloatField(default=0)),
                ('soi_nums', models.FloatField(default=0)),
                ('soi_caiid', models.IntegerField(default=0)),
                ('soi_caibupin', models.CharField(max_length=64)),
                ('soi_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Sendorder')),
            ],
            options={
                'db_table': 'fly_sendorder_items',
            },
        ),
        migrations.CreateModel(
            name='Sendcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_price', models.FloatField(default=0)),
                ('s_cai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Cairecord')),
                ('s_kuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Pants')),
                ('s_wname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Worker')),
            ],
            options={
                'db_table': 'fly_sendcart',
            },
        ),
        migrations.CreateModel(
            name='Orderbus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_bupi', models.CharField(max_length=100)),
                ('o_price', models.FloatField(default=0)),
                ('o_meter', models.FloatField(default=0)),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Order')),
            ],
            options={
                'db_table': 'fly_order_bus',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_meter', models.FloatField(default=0)),
                ('c_bupi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Bupi')),
            ],
            options={
                'db_table': 'fly_cart',
            },
        ),
    ]
