# Generated by Django 2.2 on 2020-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_sendorder_s_o_is_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendorderitems',
            name='soi_nums',
            field=models.IntegerField(default=0),
        ),
    ]
