# Generated by Django 2.2 on 2020-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20200219_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flyuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=32, unique=True)),
                ('u_password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'fly_user',
            },
        ),
    ]
