# Generated by Django 2.2 on 2020-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_flyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cairecord',
            name='cai_sign',
            field=models.BooleanField(default=False),
        ),
    ]
